# Example: Migrated karma-admin-api workflow
name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (v1.0.0, v2.1.3-dev, etc.)
  pull_request:
    branches:
      - master
      - main
      - development
      - production

jobs:
  pipeline:
    uses: karmadev/karma-workflows/.github/workflows/node-service-pipeline.yml@main
    with:
      service-name: karma-admin-api
      working-directory: backend
      has-graphql: true
      apollo-graph: karma-admin
      apollo-subgraph: Base
      schema-path: ./schema.gql
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
      APOLLO_KEY: ${{ secrets.APOLLO_KEY_ADMIN }}