name: Deploy Website to Firebase

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
      branch:
        description: 'Branch to deploy'
        required: false
        default: 'main'

jobs:
  deploy:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout website repository
        uses: actions/checkout@v4
        with:
          repository: karmadev/website-temp-2025
          ref: ${{ github.event.inputs.branch || 'main' }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Next.js application
        run: npm run build
        env:
          NODE_ENV: production
      
      - name: Export static files
        run: npm run export || npx next export
        continue-on-error: true
      
      - name: Install Firebase tools
        run: npm install -g firebase-tools
      
      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy \
            --only hosting \
            --project karma-website-production \
            --token "${{ secrets.FIREBASE_TOKEN }}"
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
      
      - name: Get deployment URL
        run: |
          echo "🚀 Deployment complete!"
          echo "Production URL: https://karma.life"
          echo "Alternative URL: https://www.karma.life"
          echo "Firebase URL: https://karma-website-production.web.app"
      
      - name: Post deployment notification
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const status = '${{ job.status }}';
            const environment = '${{ github.event.inputs.environment }}';
            const branch = '${{ github.event.inputs.branch || 'main' }}';
            
            const message = status === 'success' 
              ? `✅ Website deployed successfully to ${environment} from branch ${branch}`
              : `❌ Website deployment to ${environment} failed from branch ${branch}`;
            
            console.log(message);