name: Firebase App CI/CD Pipeline

on:
  workflow_call:
    inputs:
      project-name:
        description: 'Firebase project name'
        type: string
        required: true
      firebase-project-dev:
        description: 'Firebase project ID or alias for development'
        type: string
        required: true
      firebase-project-prod:
        description: 'Firebase project ID or alias for production'
        type: string
        required: true
      node-version:
        description: 'Node.js version'
        type: string
        required: false
        default: '18'
      working-directory:
        description: 'Working directory'
        type: string
        required: false
        default: '.'
      build-command:
        description: 'Build command (overrides env-specific commands)'
        type: string
        required: false
      build-command-dev:
        description: 'Build command for development'
        type: string
        required: false
        default: 'npm run build:dev'
      build-command-prod:
        description: 'Build command for production'
        type: string
        required: false
        default: 'npm run build'
      deploy-target:
        description: 'Firebase deploy targets'
        type: string
        required: false
        default: 'hosting'
      hosting-target:
        description: 'Firebase hosting target (overrides env-specific)'
        type: string
        required: false
      hosting-target-dev:
        description: 'Firebase hosting target for development'
        type: string
        required: false
        default: 'dev'
      hosting-target-prod:
        description: 'Firebase hosting target for production'
        type: string
        required: false
        default: 'prod'
      use-firebase-token:
        description: 'Use Firebase token instead of service account'
        type: boolean
        required: false
        default: true
    secrets:
      NPM_TOKEN:
        description: 'NPM token'
        required: false
      GCP_SA_KEY:
        description: 'GCP service account key (JSON) for Firebase authentication'
        required: false
      FIREBASE_SERVICE_ACCOUNT_DEV:
        description: 'Firebase service account for dev'
        required: false
      FIREBASE_SERVICE_ACCOUNT_PROD:
        description: 'Firebase service account for prod'
        required: false
      FIREBASE_DEPLOY_TOKEN:
        description: 'Firebase deployment token'
        required: false
      SENTRY_AUTH_TOKEN:
        description: 'Sentry auth token'
        required: false
      SLACK_WEBHOOK_URL:
        description: 'Slack webhook URL for notifications'
        required: false

jobs:
  determine-environment:
    uses: ./.github/workflows/determine-env.yml
  
  test:
    uses: ./.github/workflows/node-test.yml
    with:
      node-version: ${{ inputs.node-version }}
      working-directory: ${{ inputs.working-directory }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  
  deploy:
    needs: [determine-environment, test]
    if: needs.determine-environment.outputs.should-deploy == 'true'
    uses: ./.github/workflows/deploy-firebase.yml
    with:
      project-id: ${{ needs.determine-environment.outputs.environment == 'production' && inputs.firebase-project-prod || inputs.firebase-project-dev }}
      environment: ${{ needs.determine-environment.outputs.environment }}
      working-directory: ${{ inputs.working-directory }}
      node-version: ${{ inputs.node-version }}
      build-command: ${{ inputs.build-command }}
      build-command-dev: ${{ inputs.build-command-dev }}
      build-command-prod: ${{ inputs.build-command-prod }}
      deploy-target: ${{ inputs.deploy-target }}
      hosting-target: ${{ inputs.hosting-target }}
      hosting-target-dev: ${{ inputs.hosting-target-dev }}
      hosting-target-prod: ${{ inputs.hosting-target-prod }}
      version: ${{ needs.determine-environment.outputs.version }}
      use-firebase-token: ${{ inputs.use-firebase-token }}
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.GCP_SA_KEY || (needs.determine-environment.outputs.environment == 'production' && secrets.FIREBASE_SERVICE_ACCOUNT_PROD || secrets.FIREBASE_SERVICE_ACCOUNT_DEV) }}
      FIREBASE_DEPLOY_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}